// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwVfHLxMoqsjr3wVuVayBWC1jI9h6680',
    appId: '1:715070587636:android:f5cbce3bf49e059fc494a1',
    messagingSenderId: '715070587636',
    projectId: 'new-petrol-477fd',
    storageBucket: 'new-petrol-477fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxiTFa4qNHqfq1C_pmDR0YFC_d6QEK-MA',
    appId: '1:715070587636:ios:0454904185865ef2c494a1',
    messagingSenderId: '715070587636',
    projectId: 'new-petrol-477fd',
    storageBucket: 'new-petrol-477fd.firebasestorage.app',
    iosBundleId: 'Octane.com.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM8m4_jQvFFD4I5fFAS-TcD_NkZIZPJ5o',
    appId: '1:715070587636:web:008f5e8ec7d69b16c494a1',
    messagingSenderId: '715070587636',
    projectId: 'new-petrol-477fd',
    authDomain: 'new-petrol-477fd.firebaseapp.com',
    storageBucket: 'new-petrol-477fd.firebasestorage.app',
    measurementId: 'G-54ZPQ7ZQNK',
  );

}